program calendar;
var m,c :integer;r:char;
begin
writeln('*********************************** ');
writeln('*    €   ’ €    Version 1.7    *') ;
writeln('***********************************') ;
repeat
 writeln('‚¢¥¤¨â¥ ¬¥áïæ (11-12) (1999)(ç¨á«®¬)');
 read(m);
until (m=11) or (m=12);
case m of
11:begin
   repeat
   writeln('¢¢¥¤¨â¥ ç¨á«® (1 -30)');
   read(c);
   until (c>0) and (c<31);
   case c of
   1 :writeln('C­®ç¨!');
   2 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
   3 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
   4 :writeln('‚­®çì!');
   5 :writeln('C­®ç¨!');
   6 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
   7 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
   8 :writeln('‚­®çì!');
   9 :writeln('C­®ç¨!');
  10 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  11 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  12 :writeln('‚­®çì!');
  13 :writeln('C­®ç¨!');
  14 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  15 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  16 :writeln('‚­®çì!');
  17 :writeln('C­®ç¨!');
  18 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  19 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  20 :writeln('‚­®çì!');
  21 :writeln('C­®ç¨!');
  22 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  23 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  24 :writeln('‚­®çì!');
  25 :writeln('C­®ç¨!');
  26 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  27 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  28 :writeln('‚­®çì!');
  29 :writeln('C­®ç¨!');
  30 :writeln('‚¥áì ¤¥­ì ¤®¬ !')
  end
  end;
12:begin
   repeat
   writeln('‚¢¥¤¨â¥ ç¨á«® (1 -31)');
   read(c);
   until (c>0) and (c<32);
   case c of
   1 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
   2 :writeln('‚­®çì!');
   3 :writeln('C­®ç¨!');
   4 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
   5 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
   6 :writeln('‚­®çì!');
   7 :writeln('C­®ç¨!');
   8 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
   9 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  10 :writeln('‚­®çì!');
  11 :writeln('C­®ç¨!');
  12 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  13 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  14 :writeln('‚­®çì!');
  15 :writeln('C­®ç¨!');
  16 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  17 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  18 :writeln('‚­®çì!');
  19 :writeln('C­®ç¨!');
  20 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  21 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  22 :writeln('‚­®çì!');
  23 :writeln('C­®ç¨!');
  24 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  25 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  26 :writeln('‚­®çì!');
  27 :writeln('C­®ç¨!');
  28 :writeln('‚¥áì ¤¥­ì ¤®¬ !');
  29 :writeln(' ¡®â ¥èì ¢¥áì ¤¥­ì!');
  30 :writeln('‚­®çì!');
  31 :writeln('C­®ç¨!');

  end
  end;

  end

  end.
