comment `#####################################################
#
#  ISO639-1.inc    19.01.2007 by fnt0m32 'at' gmail.com
#
#  Part of list for 'kli' project
#
##############################################################`

LANG_CODE_COUNT	equ 66h

lang_code		db	"  "		; 0x00 LANG_NEUTRAL Neutral

db "AR"     ; 0x01 LANG_ARABIC Arabic
db "BG"     ; 0x02 LANG_BULGARIAN Bulgarian
db "CA"     ; 0x03 LANG_CATALAN Catalan
db "ZH"     ; 0x04 LANG_CHINESE Chinese
db "CS"     ; 0x05 LANG_CZECH Czech
db "DA"     ; 0x06 LANG_DANISH Danish
db "DE"     ; 0x07 LANG_GERMAN German
db "EL"     ; 0x08 LANG_GREEK Greek
db "EN"     ; 0x09 LANG_ENGLISH English
db "ES"     ; 0x0a LANG_SPANISH Spanish
db "FI"     ; 0x0b LANG_FINNISH Finnish
db "FR"     ; 0x0c LANG_FRENCH French
db "HE"     ; 0x0d LANG_HEBREW Hebrew
db "HU"     ; 0x0e LANG_HUNGARIAN Hungarian
db "IS"     ; 0x0f LANG_ICELANDIC Icelandic
db "IT"     ; 0x10 LANG_ITALIAN Italian
db "JA"     ; 0x11 LANG_JAPANESE Japanese
db "KO"     ; 0x12 LANG_KOREAN Korean
db "NL"     ; 0x13 LANG_DUTCH Dutch
db "NN"     ; 0x14 LANG_NORWEGIAN Norwegian
db "PL"     ; 0x15 LANG_POLISH Polish
db "PT"     ; 0x16 LANG_PORTUGUESE Portuguese
db "  "     ; 0x17
db "RO"     ; 0x18 LANG_ROMANIAN Romanian
db "RU"     ; 0x19 LANG_RUSSIAN Russian
db "SH"     ; 0x1a LANG_CROATIAN Croatian
;db "SR"    ; 0x1a LANG_SERBIAN Serbian
db "SK"     ; 0x1b LANG_SLOVAK Slovak
db "SQ"     ; 0x1c LANG_ALBANIAN Albanian
db "SV"     ; 0x1d LANG_SWEDISH Swedish
db "TH"     ; 0x1e LANG_THAI Thai
db "TR"     ; 0x1f LANG_TURKISH Turkish
db "UR"     ; 0x20 LANG_URDU Urdu
db "ID"     ; 0x21 LANG_INDONESIAN Indonesian
db "UK"     ; 0x22 LANG_UKRAINIAN Ukrainian
db "BE"     ; 0x23 LANG_BELARUSIAN Belarusian
db "SL"     ; 0x24 LANG_SLOVENIAN Slovenian
db "ET"     ; 0x25 LANG_ESTONIAN Estonian
db "LV"     ; 0x26 LANG_LATVIAN Latvian
db "LT"     ; 0x27 LANG_LITHUANIAN Lithuanian
db "  "     ; 0x28
db "  "     ; 0x29 LANG_FARSI Farsi
db "VI"     ; 0x2a LANG_VIETNAMESE Vietnamese
db "HY"     ; 0x2b LANG_ARMENIAN Armenian
db "AZ"     ; 0x2c LANG_AZERI Azeri
db "EU"     ; 0x2d LANG_BASQUE Basque
db "  "     ; 0x2e
db "MK"     ; 0x2f LANG_MACEDONIAN Macedonian (FYROM)
db "  "     ; 0x30
db "  "     ; 0x31
db "  "     ; 0x32
db "  "     ; 0x33
db "  "     ; 0x34
db "  "     ; 0x35
db "AF"     ; 0x36 LANG_AFRIKAANS Afrikaans
db "KA"     ; 0x37 LANG_GEORGIAN Georgian
db "  "     ; 0x38 LANG_FAEROESE Faeroese
db "HI"     ; 0x39 LANG_HINDI Hindi
db "  "     ; 0x3a
db "  "     ; 0x3b
db "  "     ; 0x3c
db "  "     ; 0x3d
db "MS"     ; 0x3e LANG_MALAY Malay
db "KK"     ; 0x3f LANG_KAZAK Kazak
db "KY"     ; 0x40 LANG_KYRGYZ Kyrgyz
db "SW"     ; 0x41 LANG_SWAHILI Swahili
db "  "     ; 0x42
db "UZ"     ; 0x43 LANG_UZBEK Uzbek
db "TT"     ; 0x44 LANG_TATAR Tatar
db "BN"     ; 0x45 LANG_BENGALI Not supported.
db "PA"     ; 0x46 LANG_PUNJABI Punjabi
db "GU"     ; 0x47 LANG_GUJARATI Gujarati
db "OR"     ; 0x48 LANG_ORIYA Not supported.
db "TA"     ; 0x49 LANG_TAMIL Tamil 
db "TE"     ; 0x4a LANG_TELUGU Telugu
db "KN"     ; 0x4b LANG_KANNADA Kannada
db "ML"     ; 0x4c LANG_MALAYALAM Not supported.
db "AS"     ; 0x4d LANG_ASSAMESE Not supported.
db "MR"     ; 0x4e LANG_MARATHI Marathi
db "SA"     ; 0x4f LANG_SANSKRIT Sanskrit
db "MN"     ; 0x50 LANG_MONGOLIAN Mongolian
db "  "     ; 0x51
db "  "     ; 0x52
db "  "     ; 0x53
db "  "     ; 0x54
db "  "     ; 0x55
db "GL"     ; 0x56 LANG_GALICIAN Galician
db "  "     ; 0x57 LANG_KONKANI Konkani
db "  "     ; 0x58 LANG_MANIPURI Not supported.
db "SD"     ; 0x59 LANG_SINDHI Not supported.
db "  "     ; 0x5a LANG_SYRIAC Syriac
db "  "     ; 0x5b
db "  "     ; 0x5c
db "  "     ; 0x5d
db "  "     ; 0x5e
db "  "     ; 0x5f
db "KS"     ; 0x60 LANG_KASHMIRI Not supported.
db "NE"     ; 0x61 LANG_NEPALI Not supported.
db "  "     ; 0x62
db "  "     ; 0x63
db "  "     ; 0x64
db "DV"     ; 0x65 LANG_DIVEHI Divehi