unit Unit1;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  Gradient;

type
  TForm1 = class(TForm)
    Gradient1: TGradient;
    Gradient2: TGradient;
    Gradient3: TGradient;
    Gradient4: TGradient;
    Gradient5: TGradient;
    Gradient6: TGradient;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form1: TForm1;

implementation

{$R *.DFM}

end.
